# paper/summarize.py
"""Gemini-based summarization for the paper feed's card description.

Raw academic abstracts are dense, jargon-heavy, and (for survey papers especially) long enough
to make the card's expanded view feel cramped even with unlimited scroll room. Each paper's
`description` shown in the UI is instead a short (<=200 word) plain-English summary generated by
Gemini from its abstract. When a paper has no abstract anywhere (OpenAlex/Semantic
Scholar/Crossref all came up empty), this falls back to downloading the paper's open-access PDF
and summarizing its extracted text instead of dropping the paper outright.

Uses langchain-google-genai rather than the raw google-generativeai SDK so the same LLM wrapper
can be reused by the per-paper chat agent (paper/chat.py).
"""
import asyncio
import logging
import os
import tempfile
from typing import Dict, Optional

import aiohttp

from config import Config

config_instance = Config()
logger = logging.getLogger("paperbites.summarize")

_MODEL_NAME = "gemini-2.5-flash"
_MAX_SUMMARY_WORDS = 200
# Cap how much extracted PDF text goes into the prompt - full papers can be tens of thousands of
# words, and we only need enough to produce a good summary, not the whole document.
_PDF_TEXT_CHAR_LIMIT = 15000

# The free tier for gemini-2.5-flash caps at 5 requests/minute - easy to blow through within the
# first couple of papers of a single fetch-latest run if calls just fire concurrently and react
# to 429s after the fact (each one then burns 30-45s on Google's own suggested retry delay,
# often several papers' worth at once). Serializing calls with a minimum spacing instead paces
# requests proactively, so the whole run is both faster and doesn't hammer the API with requests
# that are guaranteed to be rejected.
_gemini_rate_limit_lock = asyncio.Lock()
_gemini_next_call_time = 0.0


def _gemini_min_interval_seconds() -> float:
    rpm = config_instance.get("api.gemini_requests_per_minute", 5) or 5
    return 60.0 / max(int(rpm), 1)


async def _wait_for_gemini_rate_limit() -> None:
    global _gemini_next_call_time
    async with _gemini_rate_limit_lock:
        loop = asyncio.get_event_loop()
        now = loop.time()
        wait = _gemini_next_call_time - now
        if wait > 0:
            await asyncio.sleep(wait)
            now = loop.time()
        _gemini_next_call_time = now + _gemini_min_interval_seconds()

_SUMMARY_PROMPT = (
    "You are writing a short, plain-English summary of a research paper for a general-audience "
    "app feed. Summarize the following paper in under {max_words} words. Focus on what the "
    "researchers did, what they found, and why it matters to a non-expert reader. Write flowing "
    "prose with no headers, bullet points, or preamble like 'This paper' - just the summary "
    "itself.\n\n"
    "Title: {title}\n\n"
    "{source_label}:\n{text}"
)


def _get_llm():
    """Lazily build the Gemini chat model. Returns None if no API key is configured, so callers
    can fall back to the raw abstract instead of hard-failing when Gemini isn't set up."""
    api_key = config_instance.get("api.gemini_key")
    if not api_key:
        return None
    from langchain_google_genai import ChatGoogleGenerativeAI

    return ChatGoogleGenerativeAI(model=_MODEL_NAME, google_api_key=api_key, temperature=0.3)


async def summarize_text(title: str, text: str, source_label: str = "Abstract") -> Optional[str]:
    """Summarize arbitrary paper text (abstract or full PDF text) into a <=200 word description."""
    llm = _get_llm()
    if not llm or not text:
        return None

    prompt = _SUMMARY_PROMPT.format(
        max_words=_MAX_SUMMARY_WORDS,
        title=title,
        source_label=source_label,
        text=text[:_PDF_TEXT_CHAR_LIMIT],
    )

    await _wait_for_gemini_rate_limit()
    try:
        response = await llm.ainvoke(prompt)
        summary = (response.content or "").strip()
        return summary or None
    except Exception as e:
        logger.warning(f"Gemini summarization failed for '{title}': {e}")
        return None


async def _download_pdf_text(session: aiohttp.ClientSession, url: str) -> Optional[str]:
    """Best-effort: download a PDF and extract its text layer.

    Deliberately skips OCR (unlike paper/extraction.py's video-pipeline path) - OCR needs a
    system Tesseract install and is slow, and this is only a fallback for the minority of papers
    with no abstract at all, so a PDF with no extractable text layer is simply skipped rather
    than dropped into a heavyweight OCR pass.
    """
    import fitz  # PyMuPDF - imported lazily, only needed on this no-abstract fallback path

    try:
        async with session.get(url) as response:
            if response.status != 200:
                return None
            content_type = response.headers.get("Content-Type", "")
            if "pdf" not in content_type.lower() and not url.lower().endswith(".pdf"):
                return None
            data = await response.read()
    except Exception as e:
        logger.debug(f"Error downloading PDF from '{url}': {e}")
        return None

    tmp_path = None
    try:
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
            tmp.write(data)
            tmp_path = tmp.name
        doc = fitz.open(tmp_path)
        text = "\n".join(page.get_text("text") for page in doc)
        doc.close()
        return text.strip() or None
    except Exception as e:
        logger.debug(f"Error extracting text from PDF '{url}': {e}")
        return None
    finally:
        if tmp_path:
            os.remove(tmp_path)


async def summarize_paper(session: aiohttp.ClientSession, paper: Dict) -> Optional[str]:
    """Summarize a paper's abstract, or fall back to its PDF full text if it has no abstract."""
    title = paper.get("title") or "Untitled"
    abstract = (paper.get("abstract") or "").strip()

    if abstract:
        return await summarize_text(title, abstract, source_label="Abstract")

    url = paper.get("url")
    if not url:
        return None

    full_text = await _download_pdf_text(session, url)
    if not full_text:
        return None

    return await summarize_text(title, full_text, source_label="Full paper text")
