# paper/summarize.py
"""Gemini-based summarization for the paper feed's card description.

Raw academic abstracts are dense, jargon-heavy, and (for survey papers especially) long enough
to make the card's expanded view feel cramped even with unlimited scroll room. Each paper's
`description` shown in the UI is instead a short (<=200 word) plain-English summary generated by
Gemini from its abstract. When a paper has no abstract anywhere (OpenAlex/Semantic
Scholar/Crossref all came up empty), this falls back to downloading the paper's open-access PDF
and summarizing its extracted text instead of dropping the paper outright.

Uses langchain-google-genai rather than the raw google-generativeai SDK so the same LLM wrapper
can be reused by the per-paper chat agent (paper/chat.py).
"""
import asyncio
import logging
import os
import tempfile
from typing import Dict, List, Optional

import aiohttp

from config import Config

config_instance = Config()
logger = logging.getLogger("paperbites.summarize")

# Cycled round-robin, one model per call, so each model's own separate free-tier quota absorbs
# part of the load instead of one model's 5-requests/minute cap gating the whole run. No
# verified guarantee every one of these model ids is live on a given account/API version - a
# model that 404s or otherwise errors is simply skipped in favor of the next one in the list
# (see summarize_text), so an invalid entry here just reduces the effective pool rather than
# breaking anything.
_MODEL_NAMES = [
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite",
    "gemini-3-flash",
    "gemini-3.1-flash-lite",
    "gemini-3.5-flash-lite",
    "gemini-3.6-flash",
    "gemini-3.7-flash",
    "gemini-3.8-flash",
]
_MAX_SUMMARY_WORDS = 200
# Cap how much extracted PDF text goes into the prompt - full papers can be tens of thousands of
# words, and we only need enough to produce a good summary, not the whole document.
_PDF_TEXT_CHAR_LIMIT = 15000

_model_cycle_lock = asyncio.Lock()
_next_model_index = 0
_llm_cache: Dict[str, object] = {}


def _configured_model_names() -> List[str]:
    """api.gemini_models (a list, or a comma-separated string via PAPERBITES_GEMINI_MODELS)
    overrides the built-in list above, if set."""
    configured = config_instance.get("api.gemini_models")
    if not configured:
        return _MODEL_NAMES
    if isinstance(configured, str):
        return [name.strip() for name in configured.split(",") if name.strip()]
    return list(configured)


async def _next_model_name(models: List[str]) -> str:
    """Advance the shared round-robin position by one and return the model at that slot -
    concurrent summarize_text calls each get a different model instead of piling onto the same
    one."""
    global _next_model_index
    async with _model_cycle_lock:
        name = models[_next_model_index % len(models)]
        _next_model_index += 1
        return name

_SUMMARY_PROMPT = (
    "You are writing a short, plain-English summary of a research paper for a general-audience "
    "app feed. Summarize the following paper in under {max_words} words. Focus on what the "
    "researchers did, what they found, and why it matters to a non-expert reader. Write flowing "
    "prose with no headers, bullet points, or preamble like 'This paper' - just the summary "
    "itself.\n\n"
    "Title: {title}\n\n"
    "{source_label}:\n{text}"
)


def _get_llm_for_model(model_name: str):
    """Lazily build (and cache) the Gemini chat model for one model name. Returns None if no API
    key is configured, so callers can fall back to the raw abstract instead of hard-failing when
    Gemini isn't set up."""
    api_key = config_instance.get("api.gemini_key")
    if not api_key:
        return None
    if model_name not in _llm_cache:
        from langchain_google_genai import ChatGoogleGenerativeAI

        _llm_cache[model_name] = ChatGoogleGenerativeAI(
            model=model_name, google_api_key=api_key, temperature=0.3
        )
    return _llm_cache[model_name]


async def summarize_text(title: str, text: str, source_label: str = "Abstract") -> Optional[str]:
    """Summarize arbitrary paper text (abstract or full PDF text) into a <=200 word description.

    Tries each configured model in round-robin order, moving on immediately (no delay) on any
    failure - a rate limit, an invalid/unavailable model name, or anything else - so one model's
    free-tier cap or a bad model id doesn't stall or break the whole run. Gives up only once
    every model in the list has failed for this call.
    """
    if not config_instance.get("api.gemini_key") or not text:
        return None

    prompt = _SUMMARY_PROMPT.format(
        max_words=_MAX_SUMMARY_WORDS,
        title=title,
        source_label=source_label,
        text=text[:_PDF_TEXT_CHAR_LIMIT],
    )

    models = _configured_model_names()
    for _ in range(len(models)):
        model_name = await _next_model_name(models)
        llm = _get_llm_for_model(model_name)
        if not llm:
            continue
        try:
            response = await llm.ainvoke(prompt)
            summary = (response.content or "").strip()
            if summary:
                return summary
        except Exception as e:
            logger.warning(f"Gemini model '{model_name}' failed for '{title}': {e}")

    return None


async def _download_pdf_text(session: aiohttp.ClientSession, url: str) -> Optional[str]:
    """Best-effort: download a PDF and extract its text layer.

    Deliberately skips OCR (unlike paper/extraction.py's video-pipeline path) - OCR needs a
    system Tesseract install and is slow, and this is only a fallback for the minority of papers
    with no abstract at all, so a PDF with no extractable text layer is simply skipped rather
    than dropped into a heavyweight OCR pass.
    """
    import fitz  # PyMuPDF - imported lazily, only needed on this no-abstract fallback path

    try:
        async with session.get(url) as response:
            if response.status != 200:
                return None
            content_type = response.headers.get("Content-Type", "")
            if "pdf" not in content_type.lower() and not url.lower().endswith(".pdf"):
                return None
            data = await response.read()
    except Exception as e:
        logger.debug(f"Error downloading PDF from '{url}': {e}")
        return None

    tmp_path = None
    try:
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
            tmp.write(data)
            tmp_path = tmp.name
        doc = fitz.open(tmp_path)
        text = "\n".join(page.get_text("text") for page in doc)
        doc.close()
        return text.strip() or None
    except Exception as e:
        logger.debug(f"Error extracting text from PDF '{url}': {e}")
        return None
    finally:
        if tmp_path:
            os.remove(tmp_path)


async def summarize_paper(session: aiohttp.ClientSession, paper: Dict) -> Optional[str]:
    """Summarize a paper's abstract, or fall back to its PDF full text if it has no abstract."""
    title = paper.get("title") or "Untitled"
    abstract = (paper.get("abstract") or "").strip()

    if abstract:
        return await summarize_text(title, abstract, source_label="Abstract")

    url = paper.get("url")
    if not url:
        return None

    full_text = await _download_pdf_text(session, url)
    if not full_text:
        return None

    return await summarize_text(title, full_text, source_label="Full paper text")
